export const blogInfo =[
    {
        id:1,
        title:"Supporting Startups: Truthware participates in the 1st Entrepreneurship Conference hosted by Afretec",
        info1:"The American University in Cairo hosted the first entrepreneurship workshop of the Afretec (The African Engineering and Technology Network), an international organization that aims to encourage digital growth through the collaboration of higher education and the private and public sectors throughout Africa. The event brought together the six member universities, business owners and policymakers to develop a plan to support digital transformation through innovative startups. The agenda of the workshop was to discuss Afretec's approach to entrepreneurship with selected experts working within the entrepreneurship and innovation ecosystem in Africa. Venture capital leaders, government officials, United Nations representatives, thought leaders from six African countries and prominent successful entrepreneurs came together during the event to share unique insights on the ways universities can become more involved in the creation of startups A key goal of the workshop was to build strategies for growing entrepreneurship in digital science and technologies within the Afretec network and Africa at large. Truthware CEO, Deji Macaulay was invited to participate in strategy building, share ideas, knowledge and experience around digital entrepreneurship and serve on the panel discussing the financing landscape for innovation and entrepreneurship within the African University eco-system.",
        img1:"https://static.wixstatic.com/media/d8a860_30d0023c18324ad3bf248ff802f56124~mv2.jpg/v1/fill/w_499,h_374,fp_0.50_0.50,q_90,enc_avif,quality_auto/d8a860_30d0023c18324ad3bf248ff802f56124~mv2.jpg",
        photoMembers1:"L-R: Prof. Margaret Hutchinson, Dr. Maged Ghoneima, Dr. Jennifer Batamuliza, Dr. Diaa Khalil, Dr. Surya Raghu, Mr Deji Macaulay, Ms Zeinab Kamel.",
        info2:"“Entrepreneurship is a tricky phase for a university,” explains Tim Brown, director of research and professor of engineering and public policy and electrical and computer engineering at Carnegie Mellon University Africa. “Universities know how to teach and how to research, but their role in incubating startups and accelerators is less clear. We want to help universities identify where they can be most impactful, in addition to funding innovative products.” “My goal was to show how universities can become more involved in the ecosystem of the private sector,” Deji Macaulay states. “Universities are very good at inventing things, but true innovation requires these creations to be implemented in the market, which is why connections to the private sector are key.” The African Engineering and Technology Network (Afretec) is a pan-African collaboration of technology-focused universities from across the African continent. The creation of Afretec is a defining moment for the digital transformation of Africa. The Afretec Network, founded by Carnegie Mellon, features three pillars: teaching and learning, knowledge creation and entrepreneurship.To learn more about AFRETEC, visit: ",
        date:"May 8, 2023",
        readTime:"2",
        views:"83",
        to:"/blogpost1"
    },
    {
        id:2,
        title:"TRUTHWARE SOLUTIONS INTEGRATES AIRTEL AND AXA MANSARD IN THE INSURANCE SECTOR",
        info1:"Truthware Solutions, a Business Enterprise Solutions Integrator crossed another landmark through its newest business integrated solutions, by fostering an integration between AXA MANSARD and AIRTEL Nigeria to launch an Innovative Embedded Insurance Product. In his welcome address at the product launch, the Chief Commercial Officer, Airtel Nigeria, Femi Oshinlaja stated that, “In line with Airtel’s core value, which is to deliver solutions that enrich the lives of our customers, we are pleased to partner with AXA Mansard Health, to launch a cutting-edge health bundle that will add value to our customers. This partnership aims to provide easy and pocket friendly health insurance access to Airtel users, through mobile data service”.",
        img1:"https://static.wixstatic.com/media/d8a860_cec110206d3d4392b8b036146c7c8a58~mv2.jpg/v1/fill/w_592,h_398,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/d8a860_cec110206d3d4392b8b036146c7c8a58~mv2.jpg",
        photoMembers1:"L-R: Alfred Egbai, Group Head, Emerging Markets and Digital Partnerships at AXA ; Deji Macaulay, Chief Executive Officer, Truthware Solutions; Femi Oshinlaja, Acting Chief Commercial Officer, Airtel Nigeria; Tope Adeniyi, Chief Executive Officer, AXA Mansard, and Guruman Iwundu, Head of Digital and Carrier Services , Airtel Nigeria",
        info2:"Also commenting on the launch, Tope Adeniyi, Managing Director and Chief Executive Officer, AXA Mansard stated, “We are delighted to collaborate with Airtel to make health insurance accessible through mobile services, and we believe that this is currently one of the most innovative and relevant solutions that will empower more Nigerians to conveniently access best-in-class health insurance value offerings,”.Embedded insurance is an emerging trend in the insurance industry, offering customers the convenience of purchasing insurance coverage directly through the products they are already using. Using APIs developed by Truthware, the cross-industry integration will enable millions of customers across Nigeria access health care services at affordable prices, easy registration and a minimum barrier to entry.'Embedded insurance is the future of insurance, and we are thrilled to be at the forefront of this exciting trend,' said Deji Macaulay, CEO of Truthware. Truthware is committed to digital transformation across Africa and the integration of these two industry leaders has birthed a solution to a perennial problem of health care access and affordability in Nigeria.",
        img2:"https://static.wixstatic.com/media/d8a860_c1a2db387ddc4b7e9fb2f9e783d6199d~mv2.jpeg/v1/fill/w_592,h_546,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/d8a860_c1a2db387ddc4b7e9fb2f9e783d6199d~mv2.jpeg",
        photoMembers2:"L-R Damilola Olayioye, Admin Manager; Adebayo Osidibo, Head of Product Management; Ofure Azeta, Product Manager (Insurance); Elfrieda Ezenagu, Product Manager, Gaming & Rich Media Services.",
        info3:"The Airtel AXA Mansard health bundle gives Airtel customers the opportunity to access low-cost health care consultation and treatment of primary care issues. The bundle plan is said to provide three forms of healthcare services, including telemedicine, pharmacy, and hospitalisation reimbursement, and Airtel customers can subscribe by dialing *141*44# to select the service.Customers will be able to engage hundreds of doctors using the latest AI and ChatBot technology provided by AXA and enjoy the convenience of home consultation, access to several local pharmacies (free of charge) and cash reimbursements in case of hospital visits.Commenting at the launch, Alfred Egbai, Group Head, Emerging Markets and Digital Partnerships at AXA stated, “we are committed to providing our customers with the best possible service and support. Our embedded insurance product is just one example of how we are leveraging technology to create more value for our customers to help them achieve their goals. With the additional data bundle configured by Airtel, customer can simply dial *141*44# to access the service and enjoy automated health protection. Customers can access the bundle for as low as N700 to secure 2GB of data and health coverage up to N50,000 yearly.To affirm its commitment to improve business solutions in Nigeria’s MSME ecosystem, Truthware’s CTO Mr Samuel Ishie stated that “Our API hub provides a layer of seamless connectivity towards mobile networks and we are happy to have delivered the middleware democratizing health care protection via the mobile telecoms networks. Our platform is built to be flexible, robust and scalable to manage millions of transactions.”Airtel’s Head of Digital and Carrier Services, Guruman Iwundu concluded the product presentation by saying, “the Airtel AXA-Mansard health bundle is a game-changer in the Nigerian healthcare system. Airtel is committed to delivering solutions that enrich the lives of its customers, and this health bundle is one of such solutions. We urge all Airtel customers to take advantage of this innovative service and protect themselves and their loved ones.”.Truthware which serves as a gateway for industries to access telecommunications services has carried out this activity for companies across industries for over 10 years. With a rich client portfolio which comprises of companies such as MTN, Airtel, LAMATA, CowryWifi, WiFlix, Glo and more, they are just getting started.",
        date:"May 2, 2023",
        readTime:"3",
        views:"117",
        to:"/blogpost2"
    },
    {
        id:3,
        title:"TRUTHWARE WINS ENTERPRISE COMPANY OF THE YEAR AT BUSINESSDAY: Nigerian Business Leadership Awards",
        info1:"The BusinessDay Nigerian Business Leadership Awards recognise remarkable business leaders and organisations in Nigeria for their sustained commitment to excellence in enterprise.At the awards and gala dinner which took place at the Lagos Continental Hotel, Victoria Island, Lagos, the Nigerian Business Leadership Awards were grouped in two categories: Global Awards and Sectoral Awards.The criteria for vetting was based on a balanced scorecard that assigns weighted averages to leadership, innovation, market share, process improvement, financial performance, employee job satisfaction, social and environmental focus, and compliance with extant regulatory requirements.",
        img1:"https://static.wixstatic.com/media/d8a860_403329299efe42fa9f38e6ac3c828cc1~mv2.jpeg/v1/fill/w_592,h_394,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/d8a860_403329299efe42fa9f38e6ac3c828cc1~mv2.jpeg",
        photoMembers1:"Truthware CEO, Deji Macaulay; Managing Director of BusinessDay, Dr Ogho Okiti; Truthware Chief Technical Officer, Samuel Ishie while collecting the Enterprise Award at the NBLA 2020.",
        info2:"Over 33 CEOs and companies were awarded in the multi-sectoral categories cutting-across manufacturing, IT, real estate and more. Truthware had been recognized for its efficient delivery of localized software for its partners in the telecoms, healthcare and insurance industries impacting millions of Nigerians per year. Truthware is known for its vendor/partnership approach of collaborative research and development of solutions tailored to meet its customers and industry needs.",
        img2:"https://static.wixstatic.com/media/d8a860_99a8db6041cb43e1998a7e5f96b80871~mv2.jpeg/v1/fill/w_592,h_280,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/d8a860_99a8db6041cb43e1998a7e5f96b80871~mv2.jpeg",
        info3:"Truthware serves as a gateway for multi-industry integration to digitise services and has carried out its transformation activity for companies across industries for over 10 years. With a rich client portfolio which comprises of companies such as MTN, Airtel, Atos, Simartis, LAMATA, CowryWifi, WiFlix, Glo and more, they are just getting started. ",
        date:"Dec 20, 2020",
        readTime:"1",
        views:"35",
        to: "/blogpost3"
    },
]